/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package us.physion.ovation.importer;

import java.awt.Component;
import java.io.File;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.*;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;
import org.openide.util.ChangeSupport;
import us.physion.ovation.interfaces.DatePickerUtilities;
import us.physion.ovation.interfaces.DateTimePicker;

/**
 *
 * @author huecotanks
 */
public class GetImageFilesPanel extends javax.swing.JPanel {

    private static class DateTimePickerPanel {

        private DateTimePicker picker;
        private JScrollPane pane;
        public DateTimePickerPanel(DateTimePicker p) {
            picker = p;
            pane = new JScrollPane();
            pane.setViewportView(picker);
        }
        
        public DateTimePicker getPicker()
        {
            return picker;
        }
        public JScrollPane getPane()
        {
            return pane;
        }
    }

    private FileTableModel fileTableModel = new FileTableModel();
    class FileTableModel extends DefaultTableModel 
    {
        ArrayList<FileMetadata> files = new ArrayList<FileMetadata>();
        ArrayList<DateTimePickerPanel> startPickers = new ArrayList<DateTimePickerPanel>();
        ArrayList<DateTimePickerPanel> endPickers = new ArrayList<DateTimePickerPanel>();
        ArrayList<JComboBox> timezoneComboBoxes = new ArrayList<JComboBox>();
        public int getSize() {
            return files.size();
        }

        public Object getValueAt(int row, int column) {
            FileMetadata meta = files.get(row);
            if (column == 0)
                return meta.getFile().getName();
            if (column == 1)
            {
                DateTimePickerPanel p = getPicker(row, column);
                p.getPicker().setDate(meta.getStart());
                return p.getPane();
            }
            if (column == 2)
            {
                DateTimePickerPanel p = getPicker(row, column);
                p.getPicker().setDate(meta.getEnd());
                return p.getPane();
            }
            if (column == 3)
            {
                JComboBox b = timezoneComboBoxes.get(row);
                b.getModel().setSelectedItem(Calendar.getInstance().getTimeZone());
                return b;
            }
            else
                return null;
        }
       
        public void add(FileMetadata s)
        {
            files.add(s);
            startPickers.add(new DateTimePickerPanel(DatePickerUtilities.createDateTimePicker()));
            endPickers.add(new DateTimePickerPanel(DatePickerUtilities.createDateTimePicker()));
            timezoneComboBoxes.add(new JComboBox(new DefaultComboBoxModel(){}));
        }
        
        public void remove(int i)
        {
            files.remove(i);
            startPickers.remove(i);
            endPickers.remove(i);
            timezoneComboBoxes.remove(i);
        }
        public List<FileMetadata> getFiles()
        {
            return files;
        }

        private DateTimePickerPanel getPicker(int row, int column) {
            if (column == 1)
            {
                if (row < startPickers.size())
                    return startPickers.get(row);
                
            }else if (column == 2)
            {
                if (row < endPickers.size())
                    return endPickers.get(row);
            }
            return null;
        }
    }
    ChangeSupport cs;
    /**
     * Creates new form GetImageFilesPanel
     */
    public GetImageFilesPanel(ChangeSupport cs) {
        this.cs = cs;
        initComponents();
    }

    public List<FileMetadata> getFiles()
    {
        return fileTableModel.getFiles();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addImagesButton = new javax.swing.JButton();
        upButton = new javax.swing.JButton();
        downButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        addImagesButton.setText(org.openide.util.NbBundle.getMessage(GetImageFilesPanel.class, "GetImageFilesPanel.addImagesButton.text")); // NOI18N
        addImagesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addImagesButtonActionPerformed(evt);
            }
        });

        upButton.setText(org.openide.util.NbBundle.getMessage(GetImageFilesPanel.class, "GetImageFilesPanel.upButton.text")); // NOI18N
        upButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButtonActionPerformed(evt);
            }
        });

        downButton.setText(org.openide.util.NbBundle.getMessage(GetImageFilesPanel.class, "GetImageFilesPanel.downButton.text")); // NOI18N

        jTable1.setModel(fileTableModel
        );
        jScrollPane2.setViewportView(jTable1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(addImagesButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 193, Short.MAX_VALUE)
                        .add(upButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(downButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(addImagesButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(downButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(upButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addImagesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImagesButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileFilter filter = new ImageFileFilter();
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(new JPanel());
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            for (File f : chooser.getSelectedFiles())
            {
                fileTableModel.add(new FileMetadata(f));
            }
        }
    }//GEN-LAST:event_addImagesButtonActionPerformed

    private void upButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButtonActionPerformed
        
    }//GEN-LAST:event_upButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addImagesButton;
    private javax.swing.JButton downButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton upButton;
    // End of variables declaration//GEN-END:variables
}
