/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package us.physion.ovation.editor;

import java.awt.EventQueue;
import java.util.Collection;
import javax.swing.SwingUtilities;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.Plot;
import org.jfree.chart.plot.PlotOrientation;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.Utilities;
import ovation.*;
import us.physion.ovation.interfaces.ConnectionProvider;
import org.jfree.data.*;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.Dataset;
import org.jfree.data.xy.DefaultXYDataset;
import us.physion.ovation.interfaces.IEntityWrapper;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//us.physion.ovation.editor//Editor//EN",
autostore = false)
@TopComponent.Description(preferredID = "EditorTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@ActionID(category = "Window", id = "us.physion.ovation.editor.EditorTopComponent")
@ActionReference(path = "Menu/Window" /*
 * , position = 333
 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_EditorAction",
preferredID = "EditorTopComponent")
@Messages({
    "CTL_EditorAction=Editor",
    "CTL_EditorTopComponent=Editor Window",
    "HINT_EditorTopComponent=This is a Editor window"
})
public final class EditorTopComponent extends TopComponent {
    
    Lookup.Result global;
    JFreeChart chart;
    DefaultXYDataset ds;

    private LookupListener listener = new LookupListener() {

        @Override
        public void resultChanged(LookupEvent le) {
            
            //TODO: we should have some other Interface for things that can update the tags view
            //then we could get rid of the Library dependancy on the Explorer API
            if (TopComponent.getRegistry().getActivated() instanceof ExplorerManager.Provider)
            {
                updateEntitySelection();
            }
        }

        

    };
    public EditorTopComponent() {
        ds = new DefaultXYDataset();
        chart = ChartFactory.createXYLineChart("Title", "X Label", "Y Label", ds, PlotOrientation.VERTICAL, true, true, true);
        initComponents();
        jPanel1.setVisible(false);
        setName(Bundle.CTL_EditorTopComponent());
        setToolTipText(Bundle.HINT_EditorTopComponent());
        global = Utilities.actionsGlobalContext().lookupResult(IEntityWrapper.class);
        global.addLookupListener(listener);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new ChartPanel(chart);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
    
    private void updateEntitySelection() {
        Collection<? extends IEntityWrapper> entities = global.allInstances();
        if (entities.size() == 0)
        {
            jPanel1.setVisible(false);
            return;
        }
        DefaultXYDataset ds = new DefaultXYDataset();
        String title = null;
        String xAxis = null;
        String yAxis = null;
        for (IEntityWrapper ew: entities)
        {
            if (ew.getType().isAssignableFrom(Epoch.class))
            {
                Epoch epoch = (Epoch)(ew.getEntity());//getEntity gets the context for the given thread
                for (String name: epoch.getResponseNames())
                {
                    ResponseWrapper entity = ResponseWrapper.createIfPlottable(epoch.getResponse(name));
                    if (entity == null)
                    {
                        continue;
                    }
                    title ="Responses for " + epoch.getProtocolID(); 
                    addXYDataset(ds, entity, name);
                    xAxis = entity.xUnits();
                    yAxis = entity.yUnits();
                }
                
            }
            else if (ew.getType().isAssignableFrom(Response.class)) {
                title = ew.getDisplayName();
                ResponseWrapper entity = ResponseWrapper.createIfPlottable(ew);
                if (entity != null) {
                    addXYDataset(ds, entity, ew.getDisplayName());
                    xAxis = entity.xUnits();
                    yAxis = entity.yUnits();
                }
            }
        }
        runOnEDT(updateChartRunnable(ds, title, xAxis, yAxis));
       
    }
    
    private Runnable updateChartRunnable(final DefaultXYDataset ds, final String title, final String xAxis, final String yAxis)
    {
        return new Runnable(){

            @Override
            public void run() {
                if (title == null) {
                    jPanel1.setVisible(false);
                    return;
                }
                chart.setTitle(title);
                chart.getXYPlot().setDataset(ds);
                chart.getXYPlot().setDomainAxis(new NumberAxis(xAxis));
                chart.getXYPlot().setRangeAxis(new NumberAxis(yAxis));
                chart.fireChartChanged();
                jPanel1.setVisible(true);
            }
        };
    }
    
    private void runOnEDT(Runnable r) {
        
        if (EventQueue.isDispatchThread())
        {
            r.run();
        }
        else{
            SwingUtilities.invokeLater(r);
        }
    }

    private void addXYDataset(DefaultXYDataset ds, ResponseWrapper rw, String name)
    {
        NumericData d = rw.getData();
        double samplingRate = rw.getSamplingRate();
        long[] shape = d.getShape();
        long size = 1;
        for (int dimension = 0; dimension<shape.length; dimension++)
        {
            size = size*shape[dimension];
        }
        
        if (shape.length == 1)
        {
            if (d.getDataFormat() == NumericDataFormat.FloatingPointDataType)
            {
                double[] floatingData = d.getFloatingPointData();
                double[][] data = new double[2][(int) size];
                for (int i = 0; i < (int) size; ++i) {
                    data[1][i] = floatingData[i];
                    data[0][i] = i*samplingRate;
                }
                ds.addSeries(name, data);
            }
            else if (d.getDataFormat() == NumericDataFormat.SignedFixedPointDataType)
            {
                int[] integerData = d.getIntegerData();
                double[][] data = new double[(int) size][2];
                for (int i = 0; i < (int) size; ++i) {
                    data[1][i] = integerData[i];
                    data[0][i] = i*samplingRate;
                }
                ds.addSeries(name, data);
            }
            else if (d.getDataFormat() == NumericDataFormat.UnsignedFixedPointDataType)
            {
                long[] longData = d.getUnsignedIntData();
                double[][] data = new double[(int) size][2];
                for (int i = 0; i < (int) size; ++i) {
                    data[1][i] = longData[i];
                    data[0][i] = i*samplingRate;
                }
                ds.addSeries(name, data);
            }
            
            else{
                Ovation.getLogger().debug("NumericData object has unknown type: " + d.getDataFormat());
            }
        }
    }
    
}

class ResponseWrapper
{
    String xunits;
    String yunits;
    double samplingRate;
    NumericData data;
    
    protected ResponseWrapper() {}
    
    
    static ResponseWrapper createIfPlottable(Response r)
    {
        if (!r.getUTI().equals(Response.NUMERIC_DATA_UTI) || r.getShape().length != 1)
        {
            return null;
        }
    
        ResponseWrapper rw = new ResponseWrapper();
        rw.data = r.getData();
        rw.samplingRate = r.getSamplingRates()[0];
        rw.xunits = r.getUnits();
        rw.yunits = r.getSamplingUnits()[0];
        return rw;
    }
    static ResponseWrapper createIfPlottable(IEntityWrapper ew)
    {
        return createIfPlottable((Response)ew.getEntity());
    }
    
    protected NumericData getData()
    {
        return data;
    }
    protected double getSamplingRate()
    {
        return samplingRate;
    }
    
    protected String xUnits()
    {
        return xunits;
    }
    protected String yUnits()
    {
        return yunits;
    }
}
