/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package us.physion.ovation.browser.insertion;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JPanel;
import org.joda.time.DateTime;
import org.joda.time.DateTimeZone;
import org.openide.util.ChangeSupport;

public final class InsertProjectVisualPanel1 extends JPanel {

    private ChangeSupport change;
    private String projectName;
    private String projectPurpose;
    private DateTime start;
    private DateTime end;
    
    DateTimePicker startPicker;
    DateTimePicker endPicker;
    /**
     * Creates new form InsertProjectVisualPanel1
     */
    public InsertProjectVisualPanel1(ChangeSupport cs) {
        initComponents();
        change = cs;
        projectName = "";
        projectPurpose = "";
        
        startPicker = DatePickerUtilities.createDateTimePicker();
        startPicker.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent propertyChangeEvent) {
                if ("date".equals(propertyChangeEvent.getPropertyName())) {
                    startDateTimeChanged();
                }
            }
        });
        endPicker = DatePickerUtilities.createDateTimePicker();
        endPicker.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent propertyChangeEvent) {
                if ("date".equals(propertyChangeEvent.getPropertyName())) {
                    endDateTimeChanged();
                }
            }
        });
        
        startTimezoneComboBox.setSelectedItem(DatePickerUtilities.getID(startPicker));
        endTimezoneComboBox.setSelectedItem(DatePickerUtilities.getID(endPicker));
        startPane.setViewportView(startPicker);
        endPane.setViewportView(endPicker);
        
        start = null;
        end = null;
    }

    @Override
    public String getName() {
        return "Insert Project";
    }
    
    public String getProjectName()
    {
        return projectName;
    }
    
    public String getPurpose()
    {
        return projectPurpose;
    }

    public DateTime getStart()
    {
        return start;
    }
    
    public DateTime getEnd()
    {
        return end;
    }
    
    protected void setProjectName(String name)
    {
        boolean fireChange = true;
        if (projectName.isEmpty() == name.isEmpty())
            fireChange = false;
        projectName = name;
        
        if (fireChange)
            change.fireChange();
    }
    protected void setPurpose(String p)
    {
        boolean fireChange = true;
        if (projectPurpose.isEmpty() == p.isEmpty())
            fireChange = false;
        projectPurpose = p;
        
        if (fireChange)
            change.fireChange();
    }
    protected void setStart(DateTime d)
    {
        start = d;
        change.fireChange();
    }
    protected void setEnd(DateTime d)
    {
        end = d;
        change.fireChange();
    }
    
    protected void startDateTimeChanged() {
        setStart(new DateTime(startPicker.getDate(), DateTimeZone.forID(((String)startTimezoneComboBox.getSelectedItem()))));
    }
    protected void endDateTimeChanged() {
        setEnd(new DateTime(endPicker.getDate(), DateTimeZone.forID(((String)endTimezoneComboBox.getSelectedItem()))));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        projectNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        purposeTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        startPane = new javax.swing.JScrollPane();
        endPane = new javax.swing.JScrollPane();
        startTimezoneComboBox = new javax.swing.JComboBox();
        endTimezoneComboBox = new javax.swing.JComboBox();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(InsertProjectVisualPanel1.class, "InsertProjectVisualPanel1.jLabel1.text")); // NOI18N

        projectNameTextField.setText(org.openide.util.NbBundle.getMessage(InsertProjectVisualPanel1.class, "InsertProjectVisualPanel1.projectNameTextField.text")); // NOI18N
        projectNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectNameTextFieldActionPerformed(evt);
            }
        });
        projectNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                projectNameTextFieldKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                projectNameTextFieldKeyReleased(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(InsertProjectVisualPanel1.class, "InsertProjectVisualPanel1.jLabel2.text")); // NOI18N

        purposeTextArea.setColumns(12);
        purposeTextArea.setRows(5);
        purposeTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        purposeTextArea.setPreferredSize(new java.awt.Dimension(550, 82));
        purposeTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                purposeTextAreaKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                purposeTextAreaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(purposeTextArea);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(InsertProjectVisualPanel1.class, "InsertProjectVisualPanel1.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(InsertProjectVisualPanel1.class, "InsertProjectVisualPanel1.jLabel4.text")); // NOI18N

        startPane.setBackground(new java.awt.Color(204, 204, 204));
        startPane.setBorder(null);
        startPane.setOpaque(false);
        startPane.setPreferredSize(new java.awt.Dimension(200, 30));

        endPane.setBackground(new java.awt.Color(204, 204, 204));
        endPane.setBorder(null);
        endPane.setOpaque(false);
        endPane.setPreferredSize(new java.awt.Dimension(200, 30));

        startTimezoneComboBox.setModel(new javax.swing.DefaultComboBoxModel(DatePickerUtilities.getTimeZoneIDs()));
        startTimezoneComboBox.setPreferredSize(new java.awt.Dimension(180, 30));
        startTimezoneComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTimezoneComboBoxActionPerformed(evt);
            }
        });

        endTimezoneComboBox.setModel(new javax.swing.DefaultComboBoxModel(DatePickerUtilities.getTimeZoneIDs()));
        endTimezoneComboBox.setPreferredSize(new java.awt.Dimension(180, 30));
        endTimezoneComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endTimezoneComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(endPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(startPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(startTimezoneComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(endTimezoneComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(projectNameTextField, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(projectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(startPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(startTimezoneComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(endTimezoneComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void projectNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectNameTextFieldActionPerformed
    }//GEN-LAST:event_projectNameTextFieldActionPerformed

    private void projectNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_projectNameTextFieldKeyTyped
        
    }//GEN-LAST:event_projectNameTextFieldKeyTyped

    private void purposeTextAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_purposeTextAreaKeyTyped
        
    }//GEN-LAST:event_purposeTextAreaKeyTyped

    private void purposeTextAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_purposeTextAreaKeyReleased
        setPurpose(purposeTextArea.getText());
    }//GEN-LAST:event_purposeTextAreaKeyReleased

    private void projectNameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_projectNameTextFieldKeyReleased
        setProjectName(projectNameTextField.getText());
    }//GEN-LAST:event_projectNameTextFieldKeyReleased

    private void startTimezoneComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTimezoneComboBoxActionPerformed
        setStart(new DateTime(startPicker.getDate(), DateTimeZone.forID(((String)startTimezoneComboBox.getSelectedItem()))));
    }//GEN-LAST:event_startTimezoneComboBoxActionPerformed

    private void endTimezoneComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endTimezoneComboBoxActionPerformed
        setEnd(new DateTime(endPicker.getDate(), DateTimeZone.forID(((String)endTimezoneComboBox.getSelectedItem()))));
    }//GEN-LAST:event_endTimezoneComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane endPane;
    private javax.swing.JComboBox endTimezoneComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField projectNameTextField;
    private javax.swing.JTextArea purposeTextArea;
    private javax.swing.JScrollPane startPane;
    private javax.swing.JComboBox startTimezoneComboBox;
    // End of variables declaration//GEN-END:variables

}
